version: '3.7'

services:
  app:
    image: 'backend:latest'
    build:
      context: backend/
    container_name: app
    ports:
    - 8080:8080
  web:
    image: 'web:latest'
    build:
      context: web/
    container_name: web
    ports:
    - 3000:3000
